version: '3'

services:

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespostgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  wiki:
    build: .
    image: wiki
    depends_on:
      - postgres
    environment:
      - DB_HOST=0.0.0.0
      - DB_PASSWORD=postgrespostgres
      - DB_USER=postgres
      - DB_NAME=postgres
      - DB_PORT=5432
#      - WEB_HOST=0.0.0.0
#      - WEB_PORT=8080
#      - REDIS_HOST=0.0.0.0
#      - REDIS_PORT=6379
#      - S3_HOST=http://127.0.0.1
#      - S3_PORT=9000
#      - S3_ACCESS_KEY=minio
#      - S3_SECRET_KEY=miniominio
#      - IMAGES_BUCKET=images
    command: bash -c "python main.py migrate && python main.py run"
#    network_mode: host
#    ports:
#      - "8080:8080"