[tool.isort]
profile = "black"
line_length = 120
skip = ["venv", "alembic"]
src_paths = ["src"]

[tool.black]
target-version = ["py311"]
line-length = 120

[tool.mypy]
plugins = ["sqlalchemy.ext.mypy.plugin"]
disallow_untyped_decorators = false
disallow_subclassing_any = false
python_version = 3.12
strict = true
ignore_missing_imports = true
no_implicit_optional = true
strict_equality = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true
warn_unreachable = true
exclude = ["venv", "alembic"]

[tool.flake8]
ignore = ["E501", "W291", "W503"]
#extend-exclude = ["./venv", "./alembic"]
#exclude = ["./venv", "./alembic"]
exclude = "venv"
max-complexity = 10
