"""empty message

Revision ID: 8d7a4c34f337
Revises: 9b2d9194fe69
Create Date: 2024-05-04 23:34:28.375030

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8d7a4c34f337"
down_revision: Union[str, None] = "9b2d9194fe69"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("article_day", sa.Column("title", sa.String(), nullable=True))
    op.add_column("article_good", sa.Column("title", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("article_good", "title")
    op.drop_column("article_day", "title")
    # ### end Alembic commands ###
