"""empty message

Revision ID: 9b2d9194fe69
Revises: 
Create Date: 2024-04-30 22:44:02.136943

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9b2d9194fe69"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "article_day",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("region", sa.String(), nullable=True),
        sa.Column("link", sa.String(), nullable=True),
        sa.Column("image_link", sa.String(), nullable=True),
        sa.Column("summary", sa.String(), nullable=True),
        sa.Column("send_time", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "article_good",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("region", sa.String(), nullable=True),
        sa.Column("link", sa.String(), nullable=True),
        sa.Column("image_link", sa.String(), nullable=True),
        sa.Column("summary", sa.String(), nullable=True),
        sa.Column("send_time", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "region",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("country_code", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("channel_id", sa.String(), nullable=True),
        sa.Column("utc_hour_to_send_day", sa.Integer(), nullable=True),
        sa.Column("utc_minute_to_send_day", sa.Integer(), nullable=True),
        sa.Column("intervals_for_good_article", sa.String(), nullable=True),
        sa.Column("main_page_suffix", sa.String(), nullable=True),
        sa.Column("favourite_page_suffix", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("region")
    op.drop_table("article_good")
    op.drop_table("article_day")
    # ### end Alembic commands ###
